### ISSUE TITLE
Incomplete step details in docs for dnaseq pipeline

### ISSUE THREAD

**Issue by MareikeJaniak** [c3g/GenPipes_Docs#213]
In the documentation for the step details for the dnaseq pipeline several steps only include 'TBD-GenPipes-Dev' in the description:
https://genpipes.readthedocs.io/en/genpipes-v4.4.1/user_guide/pipelines/gp_dnaseq.html#step-details

**Comment by shaloo** [comment]
@MareikeJaniak the reason is I could not find enough SME and details via READMe here for such steps: https://bitbucket.org/mugqic/genpipes/src/4.4.1/pipelines/dnaseq/#markdown-header-sym_link_final_bam.

Who can I connect with in the GenPipes Team in order to get inputs/info and replace such TBD tags with the requisite info?

cc: @ehenrion @pphector

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
I see! Yes, that should be updated in the README as well. Some of this I can pull from other pipelines that include these same steps. I'll work on filling this in with help from the others.

**Comment by MareikeJaniak** [comment]
Hi @shaloo! 
The improved README for the dnaseq pipeline is now available in dev and will be included in the next release that should be happening soon.

**Comment by shaloo** [comment]
Fixed.  Amp seq and rna seq light too had similar issues, fixed those too.
