### ISSUE TITLE
#DocReview: Hi-C and ChIP sequencing pipelines are now on RTD - need review inputs

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#23]
Please visit latest content of GenPipes Pipeline user guide at RTD:
https://genpipes.readthedocs.io/en/latest/user_guide/pipeline_ref.html

Following are the review inputs I am looking for before I get on to adding other GenPipes pipelines content on RTD:

1. Is the pipeline description framework in sync with what GenPipes users are typically familiar with? I have taken basic README.md format, and enhanced it for better information accessibility, added links (tutorials, terminology) for new users where applicable.

2. The following information is missing from README of all pipelines.  As a new user, I think this might be very helpful.  Is it okay to add a subsection for each pipeline that describes the *output* for every run? For example: Dir structure job_output, what kind of / format of files that are generated in that pipeline.  This can help the user figure out that all requisite output files are indeed generated for their run and what each is meant to contain - one line about each  output and may be what it could be used for for downstream processing (if applicable).  Let me know and I will update pipeline user guide section accordingly.

3. If the answer is yes to Q2, then what is the best way for me to obtain this information? Any guidance is welcome and I am willing to try running these on CC to see what I get.  But that output may need verification from someone who is experienced with GenPipes.

4. For existing users, is there any frequently accessed information from pipeline sources that we can add in the pipeline description TOC?  I am assuming most seasoned users don't really refer to docs other than options section? Right?

**Comment by rdali** [comment]
i am not sure I understand point #1. Can you reformulate that? We can also skype. 

2- The output of each pipeline is different depending on what the technology is and it changes with changes in the pipeline. It would be useful to add outputs but it might also be more demanding in maintenance. We should probably think of automating the output description through GenPipes so that we dont have to manually change the docs every time there are edits to the pipeline. I would say let's keep this point for later as it might need some work. 
For the time being, we can consider putting an example run of each pipeline but that would require a few hundred Gbs, so I will need to discuss it with the team.

4- Yes, you are correct. The docs are relatively recent (about 2 years old) and were scattered. So we don't have information on user access frequency beyond the number of clicks to the tutorial page.

**Comment by shaloo** [comment]
Point #1 is wrt https://genpipes.readthedocs.io/en/latest/user_guide/pipeline_ref.html content on RTD.  If you click on Hi-C description or ChIP-seq description therein, does it look ok?  I am trying to freeze the framework used to describe each pipeline in user guide.  Just wanted to make sure the sub-sections for each pipeline work for GenPipes users.  More or less, I have followed the README.md format but enhanced it as deemed appropriate for new users.  We can Skype once you have taken a look at this link and clicked on available pipeline descriptions. Thx.

**Comment by shaloo** [comment]
Let's discuss this during Friday Aug 16 Skype call and close/address accordingly.

**Comment by shaloo** [comment]
* Use Readme.md directly, push enhancements into Readme.md from RST

**Comment by shaloo** [comment]
Review Feedback (Aug 16, 2019)

* Work with Hector to ensure all 'rich-media, links' enabled content generated for Pipeline README.md files, as part of RTD documentation project, can be imported into README.md file for pipelines respectively.
* Subsequently, figure out a way of automating content display into RTD by using Pipeline specific README.md directly.

**Comment by shaloo** [comment]
Review Feedback addressed see ref #34, #35, #36, #40,  #44, and #45.
