### ISSUE TITLE
Methylseq pipeline schema updates

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#252]
@MareikeJaniak can u share debug logs for the 3 protocols of Methylation Seq Pipeline? 

1. Bismark
2. Hybrid
3. Dragen

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
The debug logs are attached here. Note that only the bismark protocol is actually widely available, since the dragen and hybrid protocols require the used of the dragen box, which is a proprietary hardware that is only available with a license from Illumina. We already have a note to that effect on the documentation, but maybe we should not include the schemas for the hybrid and dragen protocols, to avoid confusing people. @pphector What do you think? 


[methylseq_bismark.debug.log](https://github.com/user-attachments/files/15875399/methylseq_bismark.debug.log)
[methylseq_dragen.debug.log](https://github.com/user-attachments/files/15875400/methylseq_dragen.debug.log)
[methylseq_hybrid.debug.log](https://github.com/user-attachments/files/15875401/methylseq_hybrid.debug.log)

**Comment by shaloo** [comment]
@MareikeJaniak @pphector I'll try to add all three schemas for now. We can remove them later, if required. That way genuine dragon and hybrid users will have what they need as schema (if they refer to it).

**Comment by shaloo** [comment]
Updated via commit # https://github.com/c3g/GenPipes/commit/b6a735a8094338fd9f67530d74fb7784641d0b0b  cherry-picked in master branch via d321eb0. Published. closing

**Comment by shaloo** [comment]
See updates in 4.6.1  here:https://genpipes.readthedocs.io/en/genpipes-v4.6.1/user_guide/pipelines/gp_wgs_methylseq.html
For 5.0 branch here: https://genpipes.readthedocs.io/en/shaloo-gp-5.0-layout/user_guide/pipelines/gp_wgs_methylseq.html
