### ISSUE TITLE
DNA Seq 7 protocols schema to be regenerated, debug log required

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#255]
@MareikeJaniak can u share the debug logs for these 7 protocols for the new dnaseq (tumor pair merged) in 5.0?

'germline_snv', 'germline_sv', 'germline_high_cov', 'somatic_tumor_only', 'somatic_fastpass', 'somatic_ensemble', 'somatic_sv'

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
See the attached files for the debug logs. "somatic_fastpass" is not included for now, because it gave me an error I need to investigate first. 

Best, 
Mareike 

[dnaseq_germline_high_cov.debug.log](https://github.com/user-attachments/files/15874703/dnaseq_germline_high_cov.debug.log)
[dnaseq_germline_snv.debug.log](https://github.com/user-attachments/files/15874704/dnaseq_germline_snv.debug.log)
[dnaseq_germline_sv.debug.log](https://github.com/user-attachments/files/15874705/dnaseq_germline_sv.debug.log)
[dnaseq_somatic_ensemble.debug.log](https://github.com/user-attachments/files/15874706/dnaseq_somatic_ensemble.debug.log)
[dnaseq_somatic_sv.debug.log](https://github.com/user-attachments/files/15874708/dnaseq_somatic_sv.debug.log)
[dnaseq_somatic_tumor_only.debug.log](https://github.com/user-attachments/files/15874709/dnaseq_somatic_tumor_only.debug.log)

**Comment by MareikeJaniak** [comment]
The issue with dnaseq_somatic_fastpass is resolved, so here is the debug log for that last protocol:

[dnaseq_somatic_fastpass.debug.log](https://github.com/user-attachments/files/15887675/dnaseq_somatic_fastpass.debug.log)

**Comment by shaloo** [comment]
Updated and draft published for review [here](https://genpipes.readthedocs.io/en/shaloo-gp-5.0-layout/)
