### ISSUE TITLE
What's new in 5.0

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#259]
Create a new topic in docs to enable Genpipes users get started with 5.0 quickly with least hiccups.
Link it in the landing page banner prominently. Cross- Link it in user reference guide and other docs where relevant. For e.g., deployment, running on beluga in tutorial, etc.

List of items to be mentioned in that note (From Usage PoV)

* Genpipes 5.0 distribution is now Python pkg based. Earlier it was Python module based.
* Python v3.11.1 and above supported - users may need to upgrade
* New pipeline command format:  Instead of `<pipeline name>.py [options]` it is now 
`genpipes <pipeline name> [options]
* Tumor Pair and DNASeq pipelines are now merged into DNA Seq pipeline with various protocol options. Link to the user guide section
* OTHERS????

@MareikeJaniak @pphector can you guys help add / update the last bullet point above?  Is there some place on wiki where you have listed the todos for GenPipes 5.0 ?  I can filter information from there. Thx.

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 

Thanks for this!
For the usage, I think it's clearer to say:
- New pipeline command format: Instead of `<pipeline name>.py [options]` it is now
`genpipes <pipeline name> [options]`

For this bullet point, it should only mention 3.11.1 for now:

- Python v3.11.1 supported - users may need to upgrade

Additional changes:
- The `rnaseq_denovo_assembly` pipeline has been updated
- The EpiQC pipeline, HiC-Seq pipeline, and AmpliconSeq qiime protocol have been deprecated
- The DNA-Seq high coverage pipeline has also been merged into DNA-Seq (along with TumorPair)
- Markdown style reports have been deprecated throughout and replaced with MultiQC
- The methylseq pipeline has a new protocol option using gemBS (*TBD if this will be in the initial release)

**Comment by shaloo** [comment]
Addressed. See [here](https://genpipes.readthedocs.io/en/shaloo-gp-5.0-layout/).
