### ISSUE TITLE
GenPipes 5.0 Troubleshooting Guide

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#260]
List top 3-5 issues faced by new users when deploying, using genpipes 5.0. Suggest solutions/workarounds

Update existing troubleshooting guide with a new section on GenPipes 5.0 here: https://genpipes.readthedocs.io/en/genpipes-v4.6.0/development/troubleshooting_guide.html

cc: @MareikeJaniak @pphector 

Can you pls share top 3 issues faced and recommended way out / solutions for new users GenPipes 5.0?  If you'd like to have a quick huddle/call lmk.  Preferably Tue/Wed 9-10am or 11:30am-12pm Montreal, Canada time.

**Comment by MareikeJaniak** [comment]
Hi Shaloo, 
Yes, good idea. We can talk about it more, but here would be some of my suggestions, based on questions we get frequently. 

- New users sometimes don't realize that they need to also run `bash genpipes_command.sh` after running the genpipes command, so they don't understand why no jobs have been submitted. 
- Many questions and issues are due to the readset and/or design file not being formatted correctly. A reminder to double check these things with a link to the relevant page would be useful.
- Users often see very low mapping rates (close to 0%), which is usually resolved by flipping the R1 and R2 reads, so R2=FASTQ1 and R1=FASTQ2.

**Comment by shaloo** [comment]
Done

<img width="1251" alt="Screenshot 2024-09-11 at 9 31 05 PM" src="https://github.com/user-attachments/assets/3bda2343-3f37-414a-8aad-b1e3947e1c6c">
