### ISSUE TITLE
#DocSelfReview:  Need inputs for content regarding how and where to access and analyse GenPipes pipelines result

### ISSUE THREAD

**Issue by shaloo** [c3g/GenPipes_Docs#59]
This may be different for each pipeline but for the new GenPipes users, we need a conceptual section/para covering the following points.  Later - if required, we can add information specific to each pipeline in the Pipeline reference guide.

* Pipeline X run successful - where is the output generated - (local/server/shared FS)
* Pipeline X results - how to analyse them - are there specific tools per pipeline - is there a basic pre-processing required and then specialised analysis using various genomic tools?
* If a pipeline is run several times, is there a way to figure out difference in results across say 5 runs?
* Do the results also share information regarding compute/storage/time used in pipeline runs? How can a user access those logs /results?

The following Getting Started with GenPipes section needs this content:
https://genpipes.readthedocs.io/en/latest/get-started/gp_job_results.html

**Comment by rdali** [comment]
We discussed this briefly at some point, but we would need this section, if included, to be as general as possible since it would require a lot of maintenance if we go into specifics and would become obsolete very fast. 
We do have metrics for compute/time requirements for pipelines on some systems but we don't tend to share those as they depend on many variables including input size, system processing speed and other variables. We did include an excel sheet with such information in the supplementary material of the Genpipes manuscript.

**Comment by pphector** [comment]
Here is a brief overview of the GenPipes results, I'll address your points one by one. 

> Pipeline X run successful - where is the output generated - (local/server/shared FS)

When a pipeline is run successfully, by default, the output is saved to the same location the pipeline was launched in the first place. This behaviour can be changed by modifying the output directory when launching the pipeline using `-o` or `--output-dir`, for example: 
```
rnaseq.py -o /PATH/TO/OUTPUT ... (other options)
```

That being said, like Rola mentioned, what is actually written in the output location varies significantly between each pipeline. However, one of the output directories that is always consistent is the `job_output` directory. In that directory, you can find subdirectories that roughly correspond to each step in the pipeline, inside those are the log files. At the top, of the directory, there is a file that is named with the following convention: 
```
job_output/PIPELINE_job_list_YEAR-MM-DDTHH.MM.SS
```

Where: `PIPELINE` corresponds to the pipeline name and `YEAR-MM-DDTHH.MM.SS` to the date and time the pipeline was launched. This `job_list` file can be used to check the status of jobs (only possible for jobs run in SLURM or PBS, unfortunately I don't think this works for the docker version) using the following script: 
```
job_report.pl job_output/PIPELINE_job_list_YEAR-MM-DDTHH.MM.SS
```

Which outputs (to std out) a summary file that includes the number of jobs that completed successfully, those that failed, and those that are still active/inactive. 


> Pipeline X results - how to analyse them - are there specific tools per pipeline - is there a basic pre-processing required and then specialised analysis using various genomic tools?

This is going to vary a lot depending on each pipeline. In general, the way you analyze the outputs varies greatly depending on your final objective. For visualization, usually results have to be imported to R or Python or some alternative visualization package. However, because each of those have different requirements, it is hard for us to tell each user exactly how they have to analyze their files. 

What I recommend for most users is to first generate a report using the `--report` flag. Most pipelines support this and generate an html report that is saved under the `report` directory. That report will usually summarize the most important results in the pipeline, while providing convenient links to the locations of important output files. More advanced users can use those output files to generate their own visualizations or further analyze results using their own methods. 

> If a pipeline is run several times, is there a way to figure out difference in results across say 5 runs?

As far as I know, we currently don't support this. 

> Do the results also share information regarding compute/storage/time used in pipeline runs? How can a user access those logs /results?

Yes, the logs have this information (see above), although the formatting varies a bit between PBS and SLURM. I don't think the batch and docker versions provide this data. Additionally, the `log_report.pl` script (also see above) will output this information in a more summarized way, avoiding the need to check each log file individually. 

For more information, you can check the attached files from our RNA-seq workshop. 

[C3GAW_practical_6_visualization.pdf](https://github.com/c3g/GenPipes/files/3644244/C3GAW_practical_6_visualization.pdf)
[C3GAW_practical_7_GenpipeProgress.pdf](https://github.com/c3g/GenPipes/files/3644245/C3GAW_practical_7_GenpipeProgress.pdf)

**Comment by shaloo** [comment]
This is useful, let me go over this information and figure out how best to capture a brief conceptual model of the same that will not require any updates as things change for specific pipelines.  Will try to point to individual pipeline readme files (that could have this specific result related info, may be later if needed). Thanks @pphector , @rdali .  Closing #14 which is a duplicate of this ticket.

**Comment by shaloo** [comment]
The two pdf were indeed very useful. Thanks @pphector , all of this put together should be enough to populate some 'generic' content about viewing and analysing genpipes results.  No specifics will be mentioned in this doc but pointers to where specific info can be obtained (workshops, relevant pipeline reference guide etc.)
